include:
  - https://gitlab.cgaws.cloud/infra/ci/raw/master/capistrano.yml

variables:
  ECR_REGISTRY: 031993550471.dkr.ecr.eu-west-1.amazonaws.com

.yarn-cache:
  cache:
    key: yarn
    paths:
    - node-modules/

eslint:
  stage: test
  image: node:8-alpine
  before_script:
    - apk --no-cache add git
    - yarn install
  script:
    - yarn eslint
  except:
    variables:
      - $ESLINT_DISABLED

stylelint:
  stage: test
  image: node:8-alpine
  before_script:
    - apk --no-cache add git
    - yarn install
  script:
    - yarn stylelint
  except:
    variables:
      - $STYLELINT_DISABLED

test-unit:
  stage: test
  image: node:8-alpine
  before_script:
    - apk --no-cache add git
    - yarn install
  script:
    - yarn test:unit
  except:
    variables:
      - $TEST_UNIT_DISABLED
