include:
  - project: infra/ci
    file: capistrano.yml
    ref: feature/capistrano-rollback

  - project: infra/ci
    file: javascript.yml

acceptance:
  environment:
    name: acceptance
    url: https://www.rapido.acceptance.cgaws.cloud

production:
  when: manual
  environment:
    name: production
    url: https://www.rapido.com/
