include:
  - https://gitlab.cgaws.cloud/infra/ci/raw/master/capistrano.yml

variables:
  ECR_REGISTRY: 031993550471.dkr.ecr.eu-west-1.amazonaws.com

.yarn-cache:
  cache:
    key: yarn
    paths:
    - node-modules/

eslint:
  extends: .yarn-cache
  stage: test
  image: node:8-alpine
  before_script:
    - apk --no-cache add git
    - yarn install
  script:
    - yarn eslint
  except:
    variables:
      - $ESLINT_DISABLED

stylelint:
  extends: .yarn-cache
  stage: test
  image: node:8-alpine
  before_script:
    - apk --no-cache add git
    - yarn install
  script:
    - yarn stylelint
  except:
    variables:
      - $STYLELINT_DISABLED

test-unit:
  extends: .yarn-cache
  stage: test
  image: node:8-alpine
  before_script:
    - apk --no-cache add git
    - yarn install
  script:
    - yarn test:unit
  except:
    variables:
      - $TEST_UNIT_DISABLED

capistrano:
  script:
    - capistrano_prepare_ssh
    - capistrano_install
    - BRANCH=feature/rap-1504-merge_rapido_and_users BASTION_USER=cgdeployer bundle exec cap acceptance deploy
  only:
    - release
    - feature/rap-1504-merge_rapido_and_users

production:
  extends: capistrano
  when: manual
  only:
    - master
