version: '3'
services:
  web:
    build: .
    command: /sbin/tini -- yarn dev
    user: root
    environment:
      HOST: 0.0.0.0
      PORT: 4000
      NODE_ENV: development
      API_BROWSER: http://localhost:5000
      API_SERVER: http://gateway:5000
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  deploy:
    image: ruby
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle

volumes:
  node_modules:
  bundle:
