version: '3.7'

services:
  web:
    build:
      context: .
      target: dev
    command: /sbin/tini -- yarn dev
    environment:
      HOST: 0.0.0.0
      PORT: 4000
      NODE_ENV: development
      API_BROWSER: https://api-hub.eu-west-1.acceptance.cgaws.cloud
      API_SERVER: https://api-hub.eu-west-1.acceptance.cgaws.cloud
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  deploy:
    image: deploy
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle

volumes:
  node_modules:
  bundle:
