version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    default_assignees:
      - 'vpuscoci-cg'
      - 'jeisonhiguita'
    default_labels:
      - 'enhancement'
      - 'dependencies'
      - 'dependabot'
